everything:
  - intellij:
    - shortcuts: http://gaerfield.github.io/ide-shortcuts/
  - plantuml:
    - home: https://plantuml.com/de/
    - Hitchhiker’s Guide to PlantUML!: https://crashedmind.github.io/PlantUMLHitchhikersGuide/
    - overview in confluence: https://confluence.eudemonia-solutions.de/display/~blaschke/Test+des+konfigurierten+PlantUML-Stylesheets
    - markdown-preview-enhanced atom: https://github.com/shd101wyy/markdown-preview-enhanced
    - markdown-preview-enhanced visual studio code: https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced
  - git:
    - interactive git branching tutorial: https://learngitbranching.js.org/?locale=de_DE
    - git-extras commands: https://github.com/tj/git-extras/blob/master/Commands.md
    - fzf-keybindings: https://junegunn.kr/2016/07/fzf-git
    - fzf-keybindings-repo: https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
  - github:
    - is github down?: https://www.githubstatus.com/
    - search github-actions:
      - https://github.com/marketplace?type=actions
      - cache: https://github.com/marketplace/actions/cache
      - upload-artifact: https://github.com/actions/upload-artifact
      - deploy to github-pages: https://github.com/marketplace/actions/github-pages-action
    - keyboard-shortcuts: https://help.github.com/en/github/getting-started-with-github/keyboard-shortcuts
  - shell:
    - byobu: https://gist.github.com/jshaw/5255721
    - my dotfiles: https://github.com/gaerfield/dotfiles
    - fzf-addons: https://github.com/junegunn/fzf/wiki/examples#git

kotlin:
  - JPA:
    - UIID for JPA entities:
      - https://jivimberg.io/blog/2018/11/05/using-uuid-on-spring-data-jpa-entities/
      - Using UUID on Spring Data JPA Entities
    - don't use data-classes for JPA:
      - https://kotlinexpertise.com/hibernate-with-kotlin-spring-boot/
      - hibernate and kotlin
  - Unit-Testing:
    - unit-testing tipps: https://phauer.com/2018/best-practices-unit-testing-kotlin/#other-useful-assertj-assertions
    - baeldung: https://www.baeldung.com/junit-5-kotlin
  - language:
    - guy with some awkward kotlin-tipps: https://agrawalsuneet.github.io/publications/
    - scope functions table (let, with, ...): https://kotlinlang.org/docs/reference/scope-functions.html#function-selection

gradle:
  - migrating from groovy to kotlin: https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/
  - multi-project builds: https://docs.gradle.org/current/userguide/multi_project_builds.html#header

spring:
  - official:
    - legacy spring docs?: https://spring.io/docs/reference
    - spring docs but different?: https://docs.spring.io/spring/docs/current/spring-framework-reference/
  - tutorials:
    - baeldung websockets: https://www.baeldung.com/websockets-spring
    - bealdung secuity acl: https://www.baeldung.com/spring-security-acl
    - spring-security dynamic ACL: http://itshrine.com/dynamically-secure-methods-by-spring-security/

about this:
  - this repo: https://github.com/gaerfield/favs
  - repos: https://github.com/gaerfield?tab=repositories
